# baseURL = 'http://example.org/'
# languageCode = 'en-us'
# title = 'Curious Duck'
# theme = "PaperMod"

baseURL = "https://curiousduck.me/"
title = "Curious Duck"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Curious Duck"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "static/img/favicon.png"
  # favicon16x16 = "static/img/favicon.ico"

  # favicon32x32 = "<link / abs url>"
  # apple_touch_icon = "<link / abs url>"
  # safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Curious Duck"
  # icon = "/apple-touch-icon.png"
  # iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Curious Duck"
  subtitle = """
  Hello world!\n
  Welcome to my blog, where I share my ideas
  """

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hello World"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/sieufernando.yiruma/"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/s.i.eu/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/vietanhnl95"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  # [params.editPost]
  # URL = "https://github.com/vietanhnl95/curious-duck-site/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about me"
name = "About Me"
url = "/about-me/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20
